spring:
  application:
    name: template
  datasource:
    #    url: jdbc:mysql://127.0.0.1:3306/wedding_host_db #主机启动配置
    url: jdbc:mysql://192.168.40.129:3306/wedding_host_db #docker 部署配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ggzst321
    type: com.zaxxer.hikari.HikariDataSource
    dbcp2:
      test-on-borrow: true
      validation-query: select 1
      test-on-return: false
      pool-prepared-statements: true
      initial-size: 8
      min-idle: 8
      max-wait-millis: 30000
      max-total:

  redis:
    host: 192.168.40.129 #redis服务
    port: 6379 #端口
    password: ggzst321 #密码
    connect-timeout: 60000 #连接超时单位ms
    lettuce:
      pool: #连接池信息
        max-active: 512 #最大连接数
        max-idle: 128 #最大空闲连接数
        min-idle: 128 #最小空闲连接数
        max-wait: 1000ms #最大连接等待时间

swagger:
  enabled: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: template-API文档


mybatis-plus:
  type-aliases-package: com.quxue.template.domain
  global-config:
    db-config:
      #全局删除字段
      logic-delete-field: status
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #standand 标准输出

minio:
  endpoint: http://101.34.204.193:9000 #服务器地址
  access-key: minioadmin #账号
  secret-key: minioadmin #密码
  bucket-name: harusame #文件上传的桶

